### PR TITLE
Various updates:

### LINKED ISSUE #1: Catch exceptions in `emit`
### Problem

`emit` doesn't catch any exceptions. This means if an exception happens in one event listener, it will prevent other event listeners for that same event from running.

### Solution

In `emit`, catch and log errors and keep looping through the rest of the event listeners.

This will make it consistent with DOM events too.

Create a new `okTurtles.events/setErrorHandler` API to set an error handler. Use try/catch. By default have an error handler that simply does `console.error('[okTurtles.events] unhandled error for event ${event}:', e)`

### LINKED ISSUE #2: Have both `on` and `once` return a function to clear the event listener
### Problem

Currently the behavior of the return value of the event listening functions is inconsistent. 

An LLM hallucinated an interesting API that I think we should adopt:

```js
      const cleanup = sbp('okTurtles.events/once', ONLINE, () => {
        setTimeout(() => {
          cleanup() // Remove the event listener
          sbp('service-worker/setup-push-subscription', (retryCount || 0) + 1)
        }, 200)
      })
```

This sort of API makes it easier to turn off event listeners.

### 

Implement this API for both `on` and `once`. Currently `once` does something similar, but it calls the event listener before unregistering it, and we should just unregister it.

### LINKED ISSUE #4: Enable Github Actions to run `npm run test`
### Problem

Tests don't actually get run.

### Solution

Use Github actions to run the tests.

You can model the workflow file after [this one](https://github.com/okTurtles/group-income/blob/master/.github/workflows/ci.yml), just remember to remove the Cypress stuff since we don't use it here.

Also get it to run `npm run lint` before running the tests. Although the linter also needs to be enabled (see #5).

### PR DESCRIPTION
**Pull request by corrideat**
* Fix #1
  * Implement #2
  * Switch to TypeScript
  * Switch to native `node:test` from mocha & sinon

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    return () => sbp('okTurtles.events/off', event, handler)
+  },
+  'okTurtles.events/once': function (event: string, handler: (...args: unknown[]) => void) {
+    const cbWithOff = (...args: unknown[]) => {
+      handler(...args)
+      sbp('okTurtles.events/off', event, cbWithOff)
+    }
+    return sbp('okTurtles.events/on', event, cbWithOff)
+  },
+  'okTurtles.events/emit': function (this: ThisType, event: string, ...data: unknown[]) {
```
Comment (taoeffect) [inline src/index.ts:31]: We can't change the selector's function signature. This needs to accept 2 arguments as before, with no `this`

Also, SBP automatically assigns a `this` - you don't need to pass it in.

File: src/index.ts [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+import '@sbp/okturtles.data'
+
+const listenKey = (evt: string) => `events/${evt}/listeners`
+
+type ThisType = {
+  errorHandler?: (event: string, e: unknown) => void
+}
+
+export default (sbp('sbp/selectors/register', {
+  'okTurtles.events/_init': function (this: ThisType) {
```
Comment (taoeffect) [inline src/index.ts:15]: SBP automatically assigns `this`, it shouldn't be passed in here like this.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice work @corrideat! Left a few comments.

What do you think about closing #4 as well so that the tests get run too?

File: src/index.ts (hunk 1 above)
Comment (corrideat) [reply src/index.ts:31]: This doesn't change the signature

File: src/index.ts (hunk 2 above)
Comment (corrideat) [reply src/index.ts:15]: This doesn't pass or define `this`. It defines the type for `this`.

**Comment by corrideat** [comment]
I could work on #4 too. (Although maybe it'll happen tomorrow).

File: src/index.ts (hunk 2 above)
Comment (taoeffect) [reply src/index.ts:15]: Can you elaborate please? Is this some TypeScript weirdness?

In regular JS this would be a function parameter called `this`....

File: src/index.ts [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    const cbWithOff = (...args: unknown[]) => {
+      handler(...args)
+      sbp('okTurtles.events/off', event, cbWithOff)
+    }
+    return sbp('okTurtles.events/on', event, cbWithOff)
+  },
+  'okTurtles.events/emit': function (this: ThisType, event: string, ...data: unknown[]) {
+    for (const listener of sbp('okTurtles.data/get', listenKey(event)) || []) {
+      try {
+        listener(...data)
```
Comment (taoeffect) [inline src/index.ts:34]: Should we have `await listener..` here? 🤔 

I have no strong preference either way just wondering what your thoughts are

File: src/index.ts (hunk 2 above)
Comment (corrideat) [reply src/index.ts:15]: This isn't TypeScript weirdness (at least, it works the same as it does in Flow, so not 'weird' in that sense), but it's indeed part of the type definitions. In JS, as you said, `this` isn't allowed as a variable name.

However, in TypeScript (and Flow), `this` as the first argument tells the type checker what type to expect for `this`.

Comment (corrideat) [reply src/index.ts:15]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#specifying-the-type-of-this-for-functions

**Review by taoeffect — APPROVED** [review]
Great work @corrideat !

File: src/index.ts (hunk 3 above)
Comment (corrideat) [reply src/index.ts:34]: I think probably we shouldn't. Having to await on `emit` would be a pretty breaking change.

Comment (taoeffect) [reply src/index.ts:34]: Fair point...

otoh, does this also mean that if the listener is async, the error handler won't catch the errors?

EDIT: I suppose that's OK. we could just say if your event listener is async, then you're responsible for error handling

Comment (corrideat) [reply src/index.ts:34]: > otoh, does this also mean that if the listener is async, the error handler won't catch the errors?

Precisely.

> we could just say if your event listener is async, then you're responsible for error handling

This sounds reasonable to me. We could also add a new selector, `handleAsync` with the await behaviour.

**Review by taoeffect — APPROVED** [review]
Fantastic work @corrideat!
